services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - node_modules:/home/vscode/app/node_modules:cached
    depends_on:
      redis:
        condition: service_healthy
      aivis:
        condition: service_healthy
    stdin_open: true
    tty: true

  aivis:
    image: tkgling/aivisspeech-engine:cuda12.8.1-cudnn-1.1.0
    ports:
      - 10101:10101
    volumes:
      - ./AivisSpeech-Engine-Dev:/home/user/.local/share/AivisSpeech-Engine-Dev:cached

  redis:
    image: redis:8.4.0
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  node_modules:
    driver: local
    name: node_modules
  redis-data:
    driver: local
    name: redis-data
